"""
Maps ATS form fields to candidate profile data.

Avoids depending on the LLM for contact fields and standardized answers
that the LLM cannot infer correctly (e.g. empty phone).

Usage: `pre_populate_answers(fields, profile)` returns a dict of known
answers, which is later merged with the answers generated by the LLM
(the LLM can overwrite if it has a better answer, but the contact
fields are guaranteed).
"""

import re
from collections.abc import Callable
from typing import Any

_RuleFn = Callable[[dict[str, Any]], str | None]


def _first_name(profile: dict[str, Any]) -> str:
    return (profile.get("name") or "").split()[0]


def _last_name(profile: dict[str, Any]) -> str:
    parts = (profile.get("name") or "").split()
    return " ".join(parts[1:]) if len(parts) > 1 else ""


def _city(profile: dict[str, Any]) -> str:
    loc = profile.get("location") or ""
    return loc.split(",")[0].strip()


def _salary_expectation(profile: dict[str, Any]) -> str:
    target = (profile.get("preferences") or {}).get("salary_target_brl_monthly")
    return str(target) if target is not None else ""


# Each entry: (regex pattern on the label, callable(profile) -> str)
# Patterns are case-insensitive and match by substring.
_RULES: list[tuple[str, _RuleFn]] = [
    # Contact (EN)
    (r"^first\s+name", _first_name),
    (r"^last\s+name", _last_name),
    (r"preferred\s+(first\s+)?name", _first_name),
    (r"^(phone|telephone|mobile|cel)", lambda p: p.get("phone") or ""),
    (r"^e-?mail", lambda p: p.get("email") or ""),
    (r"linkedin", lambda p: p.get("linkedin") or ""),
    (r"^(website|portfolio|personal\s+site)", lambda p: p.get("website") or ""),
    # Compensation — filled statically so the salary figure never reaches the LLM (E2).
    # The label must be a short *value* question: an optional lead (desired/expected/…/minimum/base/total),
    # the keyword, an optional whitelisted value-qualifier (expectation/range/salari…/…),
    # then end-of-label (allowing a SHORT trailing parenthetical/colon). Anchoring on both
    # ends with a qualifier whitelist is what rejects essay labels that merely START with
    # the keyword — "Salary history — describe…" and "Compensation philosophy: …" continue
    # into a non-whitelisted word, so they never reach `$` and fall through to the LLM.
    # The parenthetical is bounded to 15 chars: it exists for short currency/period notes
    # ("(BRL)", "(monthly)"), and an unbounded `[^)]*` reopened the essay over-match by
    # letting "Salary (please describe your history…)" slip through. Three earlier versions
    # failed here: unanchored over-matched mid-sentence mentions; start-only-anchored still
    # swallowed start-anchored essays; and an unbounded parenthetical smuggled essays in
    # parens — all silently replacing the field with a bare number. Also supports bare PT-BR
    # keywords (Salário, Faixa salarial) to match form labels in Portuguese without a lead word.
    # See the field_map test file for every regression case.
    (
        r"^(?:(?:desired|expected|current|target|minimum|base|total)\s+)?"
        r"(?:salary|compensation|pay|pretens\w*|remunera\w*|sal[aá]rio|faixa\s+salarial)"
        r"(?:\s+(?:expectations?|requirements?|range|salari\w*|pretendid\w*|desejad\w*"
        r"|mensa(?:l|is)|monthly|anual|annual|target|desired|expected))*"
        r"(?:\s*\([^)]{0,15}\))?\s*:?\s*$",
        _salary_expectation,
    ),
    # Contact (PT-BR) — "preferência" and "sobrenome" BEFORE "^nome" (order matters)
    (r"nome\s+de\s+prefer|prefer.*nome", _first_name),
    (r"^sobrenome", _last_name),
    (r"^nome", _first_name),
    (r"^(telefone|celular)", lambda p: p.get("phone") or ""),
    # Location
    (r"location\s*\(?city", _city),
    (r"localiza|^cidade", _city),
    (r"^city$", _city),
    (r"^country$", lambda p: p.get("country_en") or None),
    (r"^pa[ií]s", lambda p: p.get("country_pt") or None),
    # Work authorization / visa / sponsorship: NOT handled here — dealt with in a
    # country-dependent way in work_auth (a fixed answer would be a lie for a US job).
    # Languages
    (
        r"english\s+level|english\s+proficiency|profici.*english",
        lambda p: p.get("english_level") or None,
    ),
    # Office availability — reads from the profile; False → "No", absent → None (LLM decides)
    (
        r"work\s+from\s+the\s+office|office\s+at\s+least",
        lambda p: ("Yes" if p["office_available"] else "No") if "office_available" in p else None,
    ),
    # Current location — anchored at the start so it doesn't match confirmation
    # phrases containing "currently based" mid-sentence (e.g. "...require you to be
    # currently based...").
    (r"^where\s+are\s+you\s+(currently\s+)?based|^current\s+location|^currently\s+based", _city),
]

_COMPILED: list[tuple[re.Pattern[str], _RuleFn]] = [
    (re.compile(pattern, re.IGNORECASE), fn) for pattern, fn in _RULES
]


def _static_answer(label: str, profile: dict[str, Any]) -> str | None:
    """Answer from the first static rule matching the label (empty counts as no match).

    Exception: `_salary_expectation` always answers, even if empty — the goal is that
    the salary field NEVER falls through to the LLM to decide (E2: the figure must
    never reach the prompt), so even without a configured preference the result is ""
    rather than None.
    """
    for pattern, fn in _COMPILED:
        if pattern.search(label):
            if fn is _salary_expectation:
                return fn(profile)
            return fn(profile) or None
    return None


def pre_populate_answers(
    fields: list[str],
    profile: dict[str, Any],
    config: dict[str, Any] | None = None,
    job_location: str | None = None,
    job_remote_type: str | None = None,
) -> dict[str, str]:
    """
    Returns known answers for the fields that match the static rules
    (contact, location, language). Work-authorization fields are handled
    separately, in a country-dependent way (see work_auth). Fields with no
    match are ignored (the LLM fills them).
    """
    from gauntler.application.answers.work_auth import infer_country, resolve_work_auth

    cfg = config or {}
    country = infer_country(job_location, job_remote_type)

    result: dict[str, str] = {}
    for field_label in fields:
        clean = field_label.strip().rstrip("*").strip()
        # Work authorization is country-dependent (conservative); the rest comes
        # from the static rules. Fields with no match are left for the LLM to answer.
        answer = resolve_work_auth(clean, country, cfg)
        if answer is None:
            answer = _static_answer(clean, profile)
        if answer is not None:
            result[field_label] = answer
    return result
