"""
Maps ATS form fields to candidate profile data.

Avoids depending on the LLM for contact fields and standardized answers
that the LLM cannot infer correctly (e.g. empty phone).

Usage: `pre_populate_answers(fields, profile)` returns a dict of known
answers, which is later merged with the answers generated by the LLM
(the LLM can overwrite if it has a better answer, but the contact
fields are guaranteed).
"""

import re
from collections.abc import Callable
from typing import Any

from moonlighter.core.config import NEEDS_REVIEW_SENTINEL

_RuleFn = Callable[[dict[str, Any]], str | None]


def _first_name(profile: dict[str, Any]) -> str:
    return (profile.get("name") or "").split()[0]


def _last_name(profile: dict[str, Any]) -> str:
    parts = (profile.get("name") or "").split()
    return " ".join(parts[1:]) if len(parts) > 1 else ""


def _city(profile: dict[str, Any]) -> str:
    loc = profile.get("location") or ""
    return loc.split(",")[0].strip()


# The stored figure is BRL per month — the preference key says so. A label that
# asks for anything else (annual USD is the common case on remote-worldwide
# postings) would receive that number unconverted: "35000" read as $35,000/year
# instead of R$35.000/month is the wrong currency AND ~2.4x under the intended
# figure. Observed on a live Recruitee posting (2026-08-03), which escaped only because
# its label happens to start with "What is your", which the anchor rejects.
_FOREIGN_CURRENCY = re.compile(r"\b(usd|us\$|u\$|dollars?|eur|euros?|gbp|pounds?)\b|[€£]", re.I)
_OTHER_PERIOD = re.compile(r"\b(annual(ly)?|year(ly)?|per\s+year|p\.?a\.?|anual|ano)\b", re.I)


def _salary_expectation(profile: dict[str, Any], label: str = "") -> str:
    """The configured salary target, or NEEDS_REVIEW when the units disagree.

    Never returns None: the salary field must not fall through to the LLM (E2 —
    the figure must never reach the prompt). The sentinel keeps that property
    while refusing to state a number in units nobody verified — `is_skip` treats
    it as skip, so nothing is typed, and the service already reports sentinel
    fields as pending for the human. Converting instead would need an FX rate
    and would bake an unstated assumption into a salary negotiation.
    """
    target = (profile.get("preferences") or {}).get("salary_target_brl_monthly")
    if target is None:
        return ""
    if _FOREIGN_CURRENCY.search(label) or _OTHER_PERIOD.search(label):
        return NEEDS_REVIEW_SENTINEL
    return str(target)


# Each entry: (regex pattern on the label, callable(profile) -> str)
# Patterns are case-insensitive and match by substring.
_RULES: list[tuple[str, _RuleFn]] = [
    # Contact (EN)
    # "Full name" as a single field is the norm outside the Greenhouse/Lever
    # first+last convention; it must precede the first/last rules only in intent,
    # not in matching (the anchors are disjoint), but it must precede "^nome" in
    # the PT-BR block below, which would otherwise reduce it to a first name.
    (r"^(your\s+)?full\s+name", lambda p: p.get("name") or ""),
    (r"^first\s+name", _first_name),
    (r"^last\s+name", _last_name),
    (r"preferred\s+(first\s+)?name", _first_name),
    (r"^(phone|telephone|mobile|cel)", lambda p: p.get("phone") or ""),
    (r"^e-?mail", lambda p: p.get("email") or ""),
    (r"linkedin", lambda p: p.get("linkedin") or ""),
    (r"^(website|portfolio|personal\s+site)", lambda p: p.get("website") or ""),
    # Compensation — filled statically so the salary figure never reaches the LLM (E2).
    # The label must be a short *value* question: an optional lead (desired/expected/…/minimum/base/total),
    # the keyword, an optional whitelisted value-qualifier (expectation/range/salari…/…),
    # then end-of-label (allowing a SHORT trailing parenthetical/colon). Anchoring on both
    # ends with a qualifier whitelist is what rejects essay labels that merely START with
    # the keyword — "Salary history — describe…" and "Compensation philosophy: …" continue
    # into a non-whitelisted word, so they never reach `$` and fall through to the LLM.
    # The parenthetical is bounded to 15 chars: it exists for short currency/period notes
    # ("(BRL)", "(monthly)"), and an unbounded `[^)]*` reopened the essay over-match by
    # letting "Salary (please describe your history…)" slip through. Three earlier versions
    # failed here: unanchored over-matched mid-sentence mentions; start-only-anchored still
    # swallowed start-anchored essays; and an unbounded parenthetical smuggled essays in
    # parens — all silently replacing the field with a bare number. Also supports bare PT-BR
    # keywords (Salário, Faixa salarial) to match form labels in Portuguese without a lead word.
    # A fourth widening (2026-08-12) adds an optional interrogative lead ("What is your", "What's",
    # "Qual (é) sua") and allows the `?` on either side of the parenthetical, matching the live
    # Holepunch label "What is your expected salary? (annual USD)". It holds because the lead is a
    # closed alternation ending in "your"/"sua", so essays that continue into non-whitelisted words
    # ("What is your view on salary transparency?") still never reach `$`.
    # See the field_map test file for every regression case.
    (
        r"^(?:(?:what\s+is|what's|what\s+are)\s+your\s+|qual\s+(?:é\s+)?(?:a\s+)?sua\s+)?"
        r"(?:(?:desired|expected|current|target|minimum|base|total)\s+)?"
        r"(?:salary|compensation|pay|pretens\w*|remunera\w*|sal[aá]rio|faixa\s+salarial)"
        r"(?:\s+(?:expectations?|requirements?|range|salari\w*|pretendid\w*|desejad\w*"
        r"|mensa(?:l|is)|monthly|anual|annual|target|desired|expected))*"
        r"\s*\??\s*(?:\([^)]{0,15}\))?\s*\??\s*:?\s*$",
        _salary_expectation,
    ),
    # Contact (PT-BR) — "preferência" and "sobrenome" BEFORE "^nome" (order matters)
    (r"nome\s+de\s+prefer|prefer.*nome", _first_name),
    (r"^sobrenome", _last_name),
    (r"^nome\s+completo", lambda p: p.get("name") or ""),
    (r"^nome", _first_name),
    (r"^(telefone|celular)", lambda p: p.get("phone") or ""),
    # Location
    (r"location\s*\(?city", _city),
    (r"localiza|^cidade", _city),
    (r"^city$", _city),
    (r"^country$", lambda p: p.get("country_en") or None),
    (r"^pa[ií]s", lambda p: p.get("country_pt") or None),
    (r"^address$", lambda p: p.get("location") or None),
    # Work authorization / visa / sponsorship: NOT handled here — dealt with in a
    # country-dependent way in work_auth (a fixed answer would be a lie for a US job).
    # Languages
    (
        r"english\s+level|english\s+proficiency|profici.*english",
        lambda p: p.get("english_level") or None,
    ),
    # Office availability — reads from the profile; False → "No", absent → None (LLM decides)
    (
        r"work\s+from\s+the\s+office|office\s+at\s+least",
        lambda p: ("Yes" if p["office_available"] else "No") if "office_available" in p else None,
    ),
    # Current location — anchored at the start so it doesn't match confirmation
    # phrases containing "currently based" mid-sentence (e.g. "...require you to be
    # currently based...").
    (r"^where\s+are\s+you\s+(currently\s+)?based|^current\s+location|^currently\s+based", _city),
]

_COMPILED: list[tuple[re.Pattern[str], _RuleFn]] = [
    (re.compile(pattern, re.IGNORECASE), fn) for pattern, fn in _RULES
]


def _static_answer(label: str, profile: dict[str, Any]) -> str | None:
    """Answer from the first static rule matching the label (empty counts as no match).

    Exception: `_salary_expectation` always answers, even if empty — the goal is that
    the salary field NEVER falls through to the LLM to decide (E2: the figure must
    never reach the prompt), so even without a configured preference the result is ""
    rather than None.
    """
    for pattern, fn in _COMPILED:
        if pattern.search(label):
            if fn is _salary_expectation:
                # Called directly, not through `fn`: this is the one rule that
                # needs the label, to check the currency/period it asks for.
                return _salary_expectation(profile, label)
            return fn(profile) or None
    return None


def _clean_label(field_label: str) -> str:
    """The label a rule should match, with the form's decoration removed.

    Every rule here is ^-anchored, and forms decorate labels in ways that break
    that anchor. Workable puts the required marker on a line of its OWN, BEFORE
    the text ("*\nFirst name"), and appends the dial code after it
    ("*\nPhone\n+55"). Observed on a live posting 2026-08-04: nothing matched,
    so name, phone and the tracking email were all left for the LLM to invent.

    Only lines that are pure decoration are dropped — a marker, or a dial code.
    A label whose first line is real text keeps every line, since collapsing it
    would let unrelated rules match.
    """
    lines = [ln.strip() for ln in field_label.strip().splitlines()]
    kept = [ln for ln in lines if ln and not _DECORATION.fullmatch(ln)]
    return (kept[0] if kept else "").rstrip("*").strip()


# A line that carries no question: a required marker, or a dial code.
_DECORATION = re.compile(r"[*†‡]+|\+\d{1,4}")


def pre_populate_answers(
    fields: list[str],
    profile: dict[str, Any],
    config: dict[str, Any] | None = None,
    job_location: str | None = None,
    job_remote_type: str | None = None,
) -> dict[str, str]:
    """
    Returns known answers for the fields that match the static rules
    (contact, location, language). Work-authorization fields are handled
    separately, in a country-dependent way (see work_auth). Fields with no
    match are ignored (the LLM fills them).
    """
    from moonlighter.application.answers.work_auth import infer_country, resolve_work_auth

    cfg = config or {}
    country = infer_country(job_location, job_remote_type)

    result: dict[str, str] = {}
    for field_label in fields:
        clean = _clean_label(field_label)
        # Work authorization is country-dependent (conservative); the rest comes
        # from the static rules. Fields with no match are left for the LLM to answer.
        answer = resolve_work_auth(clean, country, cfg)
        if answer is None:
            answer = _static_answer(clean, profile)
        if answer is not None:
            result[field_label] = answer
    return result
